classvar/classvar-user-backend

.github/CODEOWNERS, .github/ISSUE_TEMPLATE/Bug.yaml, .github/ISSUE_TEMPLATE/Chore.yaml, .github/ISSUE_TEMPLATE/Feature.yaml, README.md
=> Provide GitHub flow related docs template

exam-service/src/main/java/com/classvar/examservice/application/common/EntityMapper.java, exam-service/src/main/java/com/classvar/examservice/application/dto/request/CreateOrUpdateAnnouncementDto.java, exam-service/src/main/java/com/classvar/examservice/application/dto/response/GetQuestionDto.java
=> fix: Fix EntityMApper and ExamDto

src/main/java/com/classvar/course/application/CourseCommandExecutor.java, src/main/java/com/classvar/course/domain/StareStatus.java, src/main/java/com/classvar/course/domain/StudentExamInfo.java, src/main/java/com/classvar/course/domain/StudentExamInfoRepository.java, src/main/java/com/classvar/course/infra/JpaStudentExamInfoRepository.java
=> Feature 38 add user exam info domain

src/main/java/com/classvar/manager/application/ManagerCommandExecutor.java, src/main/java/com/classvar/manager/application/ManagerQueryProcessor.java, src/main/java/com/classvar/manager/application/dto/request/CreateManagerDto.java, src/main/java/com/classvar/manager/application/dto/request/DeleteManagersDto.java, src/main/java/com/classvar/manager/application/dto/response/GetManagerDto.java, src/main/java/com/classvar/manager/application/dto/response/GetManagerListDto.java, src/main/java/com/classvar/manager/controller/ManagerCommandController.java, src/main/java/com/classvar/manager/controller/ManagerQueryController.java, src/main/java/com/classvar/manager/domain/Manager.java, src/main/java/com/classvar/manager/domain/ManagerRepository.java, src/main/java/com/classvar/manager/infra/JpaManagerRepository.java, src/main/java/com/classvar/user/domain/UserRepository.java, src/main/java/com/classvar/user/infra/JpaUserRepository.java
=> Feature 47 add manager domain

src/main/java/com/classvar/common/config/WebConfig.java, src/main/java/com/classvar/common/interceptor/LoginCheckInterceptor.java, src/main/java/com/classvar/error/ControllerAdvice.java, src/main/java/com/classvar/error/exception/UnauthenticatedUserException.java, src/main/java/com/classvar/user/application/UserQueryProcessor.java, src/main/java/com/classvar/user/application/dto/CreateOrUpdateUserDto.java, src/main/java/com/classvar/user/controller/UserCommandController.java, src/main/java/com/classvar/user/controller/UserQueryController.java, src/main/java/com/classvar/user/domain/User.java
=> Feature 46 add login fail

src/main/java/com/classvar/common/config/WebConfig.java
=> Fix:Remove swagger intercept from webconfig

src/main/java/com/classvar/exam/application/ExamCommandExecutor.java, src/main/java/com/classvar/exam/application/ExamQueryProcessor.java, src/main/java/com/classvar/exam/application/common/ExamMapper.java, src/main/java/com/classvar/exam/application/dto/request/CreateOrUpdateExamDto.java, src/main/java/com/classvar/exam/controller/ExamCommandController.java, src/main/java/com/classvar/exam/controller/ExamQueryController.java, src/main/java/com/classvar/exam/domain/Exam.java, src/main/java/com/classvar/exam/domain/ExamRepository.java, src/main/java/com/classvar/exam/infra/JpaExamRepository.java
=> Refactor: Change Controller URL Path and Related code

Dockerfile, build.gradle, docker-compose-using-image.yml, docker-compose.yml
=> chore: Dockerize the app

src/main/java/com/classvar/student/application/StudentCommandExecutor.java, src/main/java/com/classvar/student/application/StudentQueryProcessor.java, src/main/java/com/classvar/student/application/common/StudentMapper.java, src/main/java/com/classvar/student/application/dto/request/CreateStudentsDto.java, src/main/java/com/classvar/student/application/dto/request/UpdateStudentInfoDto.java, src/main/java/com/classvar/student/application/dto/request/VerifyOrDeleteStudentsDto.java, src/main/java/com/classvar/student/controller/StudentCommandController.java, src/main/java/com/classvar/student/controller/StudentQueryController.java, src/main/java/com/classvar/student/domain/Student.java, src/main/java/com/classvar/student/domain/StudentRepository.java, src/main/java/com/classvar/student/infra/JpaStudentRepository.java
=> Feature 57 refactor student domain

src/main/java/com/classvar/common/config/WebConfig.java
=> Feat: Add CORS Mapping

src/main/java/com/classvar/student/application/StudentCommandExecutor.java, src/main/java/com/classvar/student/application/dto/request/ApproveStudentsDto.java, src/main/java/com/classvar/student/application/dto/request/DeleteStudentsDto.java, src/main/java/com/classvar/student/controller/StudentCommandController.java, src/main/java/com/classvar/student/domain/Student.java
=> Feature 72 refactor student domain

.github/workflows/build_and_deploy.yml, docker-compose.yml
=> Adding CD pipeline

src/main/java/com/classvar/common/SessionConst.java, src/main/java/com/classvar/exam/application/common/ExamMapper.java, src/main/java/com/classvar/exam/controller/ExamCommandController.java, src/main/java/com/classvar/exam/domain/Exam.java, src/main/java/com/classvar/student/application/StudentQueryProcessor.java, src/main/java/com/classvar/student/controller/StudentQueryController.java
=> Feat:Implement add student instance into session attribute

.github/workflows/build_and_deploy.yml, .gitignore, docker-compose.yml, src/main/resources/application-local.yml, src/main/resources/application-prod.yml, src/main/resources/application.yml
이 PR은 로컬호스트 서버와 원격 서버에 HTTPS를 적용합니다.
=> #87 Support HTTPS

src/main/java/com/classvar/common/config/WebConfig.java
=> Fixing LoginCheckInterceptor catching login, signup API

src/main/java/com/classvar/admin/controller/AdminCommandController.java, src/main/java/com/classvar/common/config/WebConfig.java, src/main/java/com/classvar/course/controller/CourseCommandController.java, src/main/java/com/classvar/course/controller/CourseQueryController.java, src/main/java/com/classvar/exam/controller/ExamCommandController.java, src/main/java/com/classvar/exam/controller/ExamQueryController.java, src/main/java/com/classvar/manager/controller/ManagerCommandController.java, src/main/java/com/classvar/manager/controller/ManagerQueryController.java, src/main/java/com/classvar/student/controller/StudentCommandController.java, src/main/java/com/classvar/student/controller/StudentQueryController.java
=> Fix: Remove '/api' prefix from all controllers request URL

src/main/java/com/classvar/admin/application/AdminCommandExecutor.java, src/main/java/com/classvar/admin/application/common/AdminMapper.java, src/main/java/com/classvar/admin/application/common/PasswordEncoder.java, src/main/java/com/classvar/admin/domain/Admin.java, src/main/java/com/classvar/admin/infra/PasswordEncoderImpl.java
=> Feat: Add Password Hashing With Salt

docker-compose.yml
=> fix: Changed Memory Limit of Docker Container (#94)

src/main/java/com/classvar/common/config/WebConfig.java
=> fix: Fixed credential headers not being sent because of CORS (#96)

docker-compose.yml, src/main/java/com/classvar/common/config/TomcatConfig.java, src/main/resources/application-local.yml, src/main/resources/application-prod.yml
=> chore: Set Tomcat to redirect HTTP to HTTPS (#91)

src/main/java/com/classvar/admin/application/AdminCommandExecutor.java, src/main/java/com/classvar/admin/application/common/AdminMapper.java, src/main/java/com/classvar/admin/application/dto/request/CreateOrUpdateAdminDto.java, src/main/java/com/classvar/admin/application/dto/request/LoginDto.java, src/main/java/com/classvar/admin/application/dto/response/GetAdminInfoDto.java, src/main/java/com/classvar/admin/controller/AdminCommandController.java, src/main/java/com/classvar/admin/controller/AdminQueryController.java, src/main/java/com/classvar/common/SessionConst.java, src/main/java/com/classvar/common/argumentresolver/LoginUserArgumentResolver.java, src/main/java/com/classvar/common/config/SwaggerConfig.java, src/main/java/com/classvar/common/interceptor/LoginCheckInterceptor.java, src/main/java/com/classvar/exam/controller/ExamCommandController.java
=> Feat:Implement GetAdminInfo API to get self info

src/main/java/com/classvar/common/config/TomcatConfig.java, src/main/java/com/classvar/common/config/WebConfig.java, src/main/java/com/classvar/common/interceptor/SameSiteCookieInterceptor.java
closes #103 
이제 CORS 이슈는 거의 종결되었습니다.
=> fix: Added SameSite=None config
